#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# redirects to another page
# Have a custom 404 page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default #add at line 30

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@'#error_page 404 /404.html;'@'error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n'@" /etc/nginx/sites-available/default #uncomment and replace
sudo sed -i "76i \ \n\terror_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/
html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default

sudo service nginx restart
