#!/usr/bin/env bash
# This script parses Apache log files in list format.
# It displays the IP and HTTP status code of each line in the apache-access.log, which is the 1st and 9th field

awk '{print $1 " " $9}' apache-access.log
