#!/usr/bin/env bash
# displays the content of the current directory:
#  In a list format
#  Where only the part of the name after the first dash is displayed

for iter in *;
do
    echo "$iter" | cut -d'-' -f2
done
