#!/bin/bash

# Update package lists
sudo apt-get update

# Install ufw
sudo apt-get install -y ufw

# Configure ufw to block all incoming traffic, except for SSH, HTTP, and HTTPS
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp       # Allow SSH
sudo ufw allow 80/tcp       # Allow HTTP
sudo ufw allow 443/tcp      # Allow HTTPS

# Enable ufw
sudo ufw enable

# Display ufw status
sudo ufw status
